#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"

#define DRIVELINE_LEFT_FRONT_MOTORCONTROLLER_CANID 7
#define DRIVELINE_LEFT_REAR_MOTORCONTROLLER_CANID 6
#define DRIVELINE_RIGHT_FRONT_MOTORCONTROLLER_CANID 11
#define DRIVELINE_RIGHT_REAR_MOTORCONTROLLER_CANID 10

#define ARM_MOTORCONTROLLER_CANID 2
#define TURRET_MOTORCONTROLLER_CANID 3
#define TURRET_LEFTSPINNERMOTORCONTROLLER_CANID 5
#define TURRET_RIGHTSPINNERMOTORCONTROLLER_CANID 1
#define LIFT_MOTORCONTROLLER_CANID 4

#define DRIVELINE_ENCODER_INCHPERCNT 0.02934
#define ARM_ENCODER_DEGPERCNT 1
#define TURRET_ENCODER_DEGPERCNT 1
#define LIFT_ENCODER_DEGPERCNT 1

#define DRIVELINE_DRIVE_PID_P  0.05
#define DRIVELINE_DRIVE_PID_I  0.0005
#define DRIVELINE_DRIVE_PID_D  0.05
#define DRIVELINE_DRIVE_PID_F  0.25

#define DRIVELINE_TURN_PID_P  0.05
#define DRIVELINE_TURN_PID_I  0.0005
#define DRIVELINE_TURN_PID_D  0.05
#define DRIVELINE_TURN_PID_F  0.25


const int LEFTMOTOR = 1;
//const int RIGHTMOTOR = 2;

// If you are using multiple modules, make sure to define both the port
// number and the module. For example you with a rangefinder:
//const int RANGE_FINDER_PORT = 1;
//const int RANGE_FINDER_MODULE = 1;

#endif
